# Generated by Django 2.0.2 on 2018-02-02 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankmanager_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_cifno',
            field=models.DecimalField(decimal_places=0, max_digits=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
