# Generated by Django 2.0.2 on 2018-02-02 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20180202_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_cifno',
            field=models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
