# Generated by Django 2.0.2 on 2018-02-02 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20180202_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_cifno',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
