# Generated by Django 2.0.2 on 2018-02-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20180202_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ben_cusacc', models.CharField(max_length=34)),
                ('ben_name', models.CharField(max_length=50)),
                ('ben_transfer_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ben_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='bank',
            name='b_ifsc',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='b_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='ben_bankname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bname', to='bank.Bank', to_field='b_name'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='ben_ifsc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifsc', to='bank.Bank', to_field='b_ifsc'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together={('ben_cusacc', 'ben_acc')},
        ),
    ]
