# Generated by Django 2.0.2 on 2018-02-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20180202_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='ben_account_no',
            new_name='Beneficiary_account_no',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='ben_bankname',
            new_name='Beneficiary_bankname',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='ben_ifsc',
            new_name='Beneficiary_ifsc',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='ben_name',
            new_name='Beneficiary_name',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='ben_transfer_limit',
            new_name='Beneficiary_transfer_limit',
        ),
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together={('ben_cusacc', 'Beneficiary_account_no')},
        ),
    ]
